[tool.poetry]
name = "ploonetide"
version = "1.0.6"
description = "Calculate tidal interactions in planetary systems"
authors = ["Jaime A. Alvarado-Montes <rasjaime@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/JAAlvarado-Montes/ploonetide"
license = "LICENSE"
keywords = ["Tidal", "Simulation", "TESS", "Astronomy"]
include = ["README.rst", "AUTHORS.rst", "CHANGES.rst", "CONTRIBUTING.rst", "CITATION", "LICENSE"]

classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy"
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/JAAlvarado-Montes/ploonetide/issues"

[tool.poetry.dependencies]
python = ">=3.10"

# Core dependencies
argparse = ">=1.0"
astropy = ">=5.0.*"
astroplan = ">=0.7"
astroquery = ">=0.3.9"
h5py = ">=1.0"
matplotlib = ">=1.5.3"
mechanicalsoup = ">=1.0"
natsort = ">=1.0"
numpy = ">=1.18"
pandas = ">=1.1.4"
pyfiglet = ">=0.7.6"
scipy = ">=0.19.0"
tqdm = ">=4.25.0"
uncertainties = ">=1.0"

# Optional dependencies
beautifulsoup4 = { version = ">=1.0", optional = true }
black = { version = ">=21.12b0", optional = true }
bumpver = { version = ">=1.0", optional = true }
flake8 = { version = ">=3.8.4", optional = true }
furo = { version = "^2024.0.0", optional = true }
ghp-import = { version = ">=1.0.1", optional = true }
ipympl = { version = ">=0.9.7", optional = true }
ipython = { version = ">=1.0", optional = true }
ipywidgets = { version = ">=1.0", optional = true }
isort = { version = ">=5.6.4", optional = true }
jupyterlab = { version = ">=1.0", optional = true }
mypy = { version = ">=0.930", optional = true }
myst-nb = { version = "^1.0", optional = true }
myst-parser = { version = "^2.0", optional = true }
numpydoc = { version = ">=1.1.0", optional = true }
pydata-sphinx-theme = { version = ">=0.7.1", optional = true }
pylint = { version = ">=2.6.0", optional = true }
PyQt5 = { version = ">=5.15.11", optional = true }
pytest = { version = ">=6.1.2", optional = true }
pytest-cov = { version = ">=2.10.1", optional = true }
pytest-doctestplus = { version = ">=0.8.0", optional = true }
pytest-remotedata = { version = ">=0.3.2", optional = true }
pytest-xdist = { version = ">=2.1.0", optional = true }
seaborn = { version = ">=0.11.2", optional = true }
sphinx = { version = "^7.2", optional = true }
sphinx-automodapi = { version = ">=0.13", optional = true }
sphinx-autobuild = { version = "^2021.3.14", optional = true }
sphinx-copybutton = { version = "^0.5.2", optional = true }
sphinxcontrib-rawfiles = { version = ">=0.1.1", optional = true }
sphinxcontrib-restbuilder = { version = ">=0.2", optional = true }

[tool.poetry.extras]
gui = ["PyQt5"]
notebooks = ["ipympl", "ipython", "ipywidgets", "jupyterlab"]
viz = ["seaborn", "beautifulsoup4"]
docs = [
    "numpydoc", "sphinx-automodapi", "sphinxcontrib-rawfiles",
    "sphinxcontrib-restbuilder", "pydata-sphinx-theme",
    "myst-parser", "myst-nb", "sphinx", "furo"
]
dev = [
    "black", "bumpver", "flake8", "ghp-import", "isort", "mypy",
    "pylint", "pytest", "pytest-cov", "pytest-doctestplus",
    "pytest-remotedata", "pytest-xdist",
    "numpydoc", "sphinx-automodapi", "sphinxcontrib-rawfiles",
    "sphinxcontrib-restbuilder", "pydata-sphinx-theme",
    "myst-parser", "myst-nb", "sphinx", "furo", "sphinx-autobuild",
    "sphinx-copybutton"
]

[tool.poetry.group.dev.dependencies]
black = ">=21.12b0"
bumpver = ">=1.0"
flake8 = ">=3.8.4"
ghp-import = ">=1.0.1"
isort = { version = ">=5.6.4", python = ">=3.6,<4.0" }
mypy = ">=0.930"
pylint = ">=2.6.0"
pytest = ">=6.1.2"
pytest-cov = ">=2.10.1"
pytest-doctestplus = ">=0.8.0"
pytest-remotedata = ">=0.3.2"
pytest-xdist = ">=2.1.0"

# Docs (ReadTheDocs compatible)
sphinx = "^7.2"
sphinx-autobuild = "^2021.3.14"
sphinx-copybutton = "^0.5.2"
myst-parser = "^2.0"
myst-nb = "^1.0"
furo = "^2024.0.0"
numpydoc = "^1.5"

[tool.pytest.ini_options]
testpaths = ["tests", "src"]

[tool.bumpver]
current_version = "1.0.6"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message  = "Bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[tool.bumpver.file_patterns]
"pyproject.toml" = ['^current_version = "{version}"', '^version = "{version}"']
"src/ploonetide/version.py" = ['^__version__ = "{version}"']

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
